<?php

declare(strict_types=1);

namespace Strix\Ergonode\Transformer;

use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface;
use Shopware\Core\System\Tax\TaxDefinition;
use Strix\Ergonode\Provider\TaxProvider;

class ProductTaxTransformer implements ProductDataTransformerInterface
{
    private const AUTOGENERATED_TAX_NAME = 'Ergonode Autogenerated (%1$.0f%%)';

    private TaxProvider $taxProvider;

    private EntityRepositoryInterface $taxRepository;

    public function __construct(TaxProvider $taxProvider, EntityRepositoryInterface $taxRepository)
    {
        $this->taxProvider = $taxProvider;
        $this->taxRepository = $taxRepository;
    }

    public function transform(array $productData, Context $context): array
    {
        $productTaxRate = $productData['tax']['rate'] ?? null;

        if (null === $productTaxRate) {
            throw new \RuntimeException('Missing tax.rate from product data');
        }

        $taxEntity = $this->taxProvider->getByTaxRate($productTaxRate, $context);

        if (null !== $taxEntity) {
            $taxId = $taxEntity->getId();
        } else {
            $taxId = $this->taxRepository->create(
                [
                    [
                        'taxRate' => $productTaxRate,
                        'name' => \sprintf(self::AUTOGENERATED_TAX_NAME, $productTaxRate)
                    ]
                ],
                $context
            )->getPrimaryKeys(TaxDefinition::ENTITY_NAME)[0];
        }

        $productData['taxId'] = $taxId;
        unset($productData['tax']);

        return $productData;
    }
}